exchanges:
  binance:
    api_key: "your_api_key"
    secret_key: "your_secret_key"
    base_url: "https://api.binance.com/v3"
  okx:
    api_key: "your_okx_key"
    secret_key: "your_okx_secret"
    base_url: "https://open.okx.com/api/v3"